[package]
name = "rust-space-shooter-game"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.9.0-alpha.1"

[dependencies.sdl2]
sdl2 = "0.36.0"
default-features = false
features = ["image"]
